name: Build ZMK Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - board: nice_nano_v2
            shield: keyball44_left

          - board: nice_nano_v2
            shield: keyball44_right
            snippet: studio-rpc-usb-uart
            cmake-args: >
              -DCONFIG_ZMK_STUDIO=y
              -DCONFIG_ZMK_MOUSE=y
              -DCONFIG_ZMK_HID_POINTER=y

          - board: nice_nano_v2
            shield: settings_reset

    steps:
      - uses: actions/checkout@v3

      - name: Build firmware
        uses: zmkfirmware/zmk-build-action@v2
        with:
          config-path: config
          board: ${{ matrix.config.board }}
          shield: ${{ matrix.config.shield }}
          snippet: ${{ matrix.config.snippet }}
          cmake-args: ${{ matrix.config.cmake-args }}

      - uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build
