include:
  - board: nice_nano_v2
    shield: keyball_nano_left

  - board: nice_nano_v2
    shield: keyball_nano_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_ZMK_MOUSE=y
      -DCMAKE_VERBOSE_MAKEFILE=ON

  - board: nice_nano_v2
    shield: settings_reset
