name: Build Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - board: nice_nano_v2
            shield: keyball44_left
          - board: nice_nano_v2
            shield: keyball44_right
            snippet: studio-rpc-usb-uart
            cmake-args: >
              -DCONFIG_ZMK_STUDIO=y
              -DCONFIG_ZMK_MOUSE=y
              -DCONFIG_ZMK_HID_POINTER=y
          - board: nice_nano_v2
            shield: settings_reset
    steps:
      - uses: actions/checkout@v3
      - name: Build firmware
        run: |
          echo "Building for board: ${{ matrix.config.board }}, shield: ${{ matrix.config.shield }}"
          # ここに実際のビルドコマンドを記述してください
          # 例:
          # west build -d build/${{ matrix.config.shield }} -b ${{ matrix.config.board }} -- -DSHIELD=${{ matrix.config.shield }} ${{ matrix.config.cmake-args }}
